apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - app-deployment.yaml

images:
<<<<<<< HEAD
  - name: ghcr.io/aaroncallanga/cicd-pipeline
    newTag: 4f28d96
=======
  - name: ghcr.io/aaroncallanga/task-manager
    newTag: 4f28d96
>>>>>>> bef86610bf7c596ffcafbc190edca540706aa2bc

labels:
  - pairs:
      app.kubernetes.io/name: task-manager
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
