apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: task-manager

resources:
  - namespace.yaml
  - config.yaml
  - postgres.yaml
  - app-deployment.yaml

images:
  - name: ghcr.io/aaroncallanga/cicd-pipeline
    newTag: 760b386

labels:
  - pairs:
      app.kubernetes.io/name: task-manager
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
